### ISSUE TITLE
got errors during "catkin build  hand_eye_calibration_batch_estimation"

### ISSUE THREAD

**Issue by Qianboy** [ethz-asl/aslam_splines#11] opened 2018-11-08 15:29 UTC
Got many errors for same reason "marked ‘override’, but does not override", here is one example:

/home/catkin_ws/src/aslam_splines/aslam_splines/include/aslam/splines/BSplineExpressions.hpp:67:37: error: ‘virtual Eigen::Vector3d aslam
::splines::BSplinePositionExpressionNode::evaluateImplementation() const’ marked ‘override’, but does not override                       
             virtual Eigen::Vector3d evaluateImplementation() const override; 

Another error which happened lot of times is "error: invalid new-expression of abstract class type", one example:

/home/catkin_ws/src/aslam_splines/aslam_splines/src/BSplineRSPoseDesignVariable.cpp: In member function ‘aslam::backend::TransformationExpression aslam::splines::BSplineRSPoseDesignVariable::transformation(double, double)’:                                                   
/home/catkin_ws/src/aslam_splines/aslam_splines/src/BSplineRSPoseDesignVariable.cpp:67:157: error: invalid new-expression of abstract class type ‘aslam::splines::RSLineDelayTransformationExpressionNode’                                                                        
         boost::shared_ptr<RSLineDelayTransformationExpressionNode> root( new RSLineDelayTransformationExpressionNode( _bsplinePoseDV, _lineDelayDV, t0, line) );

Using gcc version of 5.5.0
Thks a lot for help!

**Comment by HannesSommer** [comment] 2018-11-09 14:49
Thanks @Qianboy , for the report. However, I cannot reproduce. I only have access to GCC 4.8, 5.4, 7.3 and CLANG 3.4, 3.8. And they are all happy with the current master. Could you please double check that you are using the current master of this repo?

**Comment by HannesSommer** [comment] 2019-04-02 09:44
Closing this for now because of no updates.

**Closed by HannesSommer** 2019-04-02 09:44 UTC
